-- MySQL Script generated by MySQL Workbench
-- mar 06 mar 2018 02:48:27 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mantenimientoPC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mantenimientoPC` ;

-- -----------------------------------------------------
-- Schema mantenimientoPC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mantenimientoPC` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mantenimientoPC` ;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Prioridad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Prioridad` (
  `pk_idPrioridad` INT(2) NOT NULL,
  `PrioridadNivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idPrioridad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Sub_TipoMantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Sub_TipoMantenimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Sub_TipoMantenimiento` (
  `pk_idSub_TipoMantenimiento` INT(2) NOT NULL,
  `descripcion` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`pk_idSub_TipoMantenimiento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`TipoMantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`TipoMantenimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`TipoMantenimiento` (
  `pk_idTipoMantenimiento` INT(2) NOT NULL,
  `fk_idSub_TipoMantenimiento` INT(2) NOT NULL,
  `descripcion` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`pk_idTipoMantenimiento`),
  INDEX `fk_TipoMantenimiento_Sub_TipoMantenimiento1_idx` (`fk_idSub_TipoMantenimiento` ASC),
  CONSTRAINT `fk_TipoMantenimiento_Sub_TipoMantenimiento1`
    FOREIGN KEY (`fk_idSub_TipoMantenimiento`)
    REFERENCES `mantenimientoPC`.`Sub_TipoMantenimiento` (`pk_idSub_TipoMantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Unidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Unidad` (
  `pk_idUnidad` INT(2) NOT NULL,
  `UnidadNombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`pk_idUnidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Solicitud` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Solicitud` (
  `pk_idSolicitud` INT(3) NOT NULL,
  `solicitante` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `correo` VARCHAR(150) NULL,
  PRIMARY KEY (`pk_idSolicitud`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`fabricantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`fabricantes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`fabricantes` (
  `pk_idFabricante` INT(4) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`pk_idFabricante`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Equipo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Equipo` (
  `pk_idNoSerie` VARCHAR(15) NOT NULL,
  `fk_PadreIdnoSerie` VARCHAR(15) NOT NULL,
  `fk_idFabricante` INT NOT NULL,
  `noInventario` VARCHAR(30) NULL,
  `partNumber` VARCHAR(20) NULL,
  `modelo` VARCHAR(45) NULL,
  `hardware_software` TINYINT(1) NOT NULL,
  `sofware` VARCHAR(45) NULL,
  `version` VARCHAR(20) NULL,
  `arquitectura3264` TINYINT(1) NULL,
  `licencia` TINYINT(1) NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`pk_idNoSerie`),
  INDEX `fk_Equipo_detalle_fabricantes1_idx` (`fk_idFabricante` ASC),
  INDEX `fk_Equipo_detalle_Equipo_detalle1_idx` (`fk_PadreIdnoSerie` ASC),
  CONSTRAINT `fk_Equipo_detalle_fabricantes1`
    FOREIGN KEY (`fk_idFabricante`)
    REFERENCES `mantenimientoPC`.`fabricantes` (`pk_idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_detalle_Equipo_detalle1`
    FOREIGN KEY (`fk_PadreIdnoSerie`)
    REFERENCES `mantenimientoPC`.`Equipo` (`pk_idNoSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`OrdenTrabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`OrdenTrabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`OrdenTrabajo` (
  `pk_idOrdenTrabajo` INT(6) NOT NULL,
  `fk_idPrioridad` INT(2) NOT NULL,
  `fk_idTipoMantenimiento` INT(2) NOT NULL,
  `fk_idUnidad` INT(2) NOT NULL,
  `fk_idOrigenSolicitud` INT(3) NOT NULL,
  `solicitudDescripcion` TEXT NULL,
  `solicitudFecha` DATE NULL,
  `clienteNombre` VARCHAR(45) NULL,
  `clienteEmail` VARCHAR(45) NULL,
  `clienteTelefono` VARCHAR(15) NULL,
  `clienteDomicilio` VARCHAR(45) NULL,
  `Estado` TINYINT(1) NOT NULL,
  `ordenTrabajoAprobadaFecha` DATE NULL,
  `tecnicoDiagnostico` TEXT NULL,
  `posibleFechaEntrega` DATE NULL,
  `Equipo_pk_idNoSerie` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`pk_idOrdenTrabajo`),
  INDEX `fk_OrdenTrabajo_Prioridad_idx` (`fk_idPrioridad` ASC),
  INDEX `fk_OrdenTrabajo_TipoMantenimiento1_idx` (`fk_idTipoMantenimiento` ASC),
  INDEX `fk_OrdenTrabajo_Unidad1_idx` (`fk_idUnidad` ASC),
  INDEX `fk_OrdenTrabajo_OrigenSolicitud1_idx` (`fk_idOrigenSolicitud` ASC),
  INDEX `fk_OrdenTrabajo_Equipo1_idx` (`Equipo_pk_idNoSerie` ASC),
  CONSTRAINT `fk_OrdenTrabajo_Prioridad`
    FOREIGN KEY (`fk_idPrioridad`)
    REFERENCES `mantenimientoPC`.`Prioridad` (`pk_idPrioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_TipoMantenimiento1`
    FOREIGN KEY (`fk_idTipoMantenimiento`)
    REFERENCES `mantenimientoPC`.`TipoMantenimiento` (`pk_idTipoMantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_Unidad1`
    FOREIGN KEY (`fk_idUnidad`)
    REFERENCES `mantenimientoPC`.`Unidad` (`pk_idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_OrigenSolicitud1`
    FOREIGN KEY (`fk_idOrigenSolicitud`)
    REFERENCES `mantenimientoPC`.`Solicitud` (`pk_idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_Equipo1`
    FOREIGN KEY (`Equipo_pk_idNoSerie`)
    REFERENCES `mantenimientoPC`.`Equipo` (`pk_idNoSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Estado` (
  `pk_idEstado` INT(2) NOT NULL,
  `EstadoNombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`pk_idEstado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Personal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Personal` (
  `pk_idPersonal` INT(3) NOT NULL,
  `fk_padrePersonal` INT(3) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dui` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `empleadoEstudiante` TINYINT(1) NOT NULL,
  `due` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idPersonal`),
  INDEX `fk_Tecnico_Tecnico1_idx` (`fk_padrePersonal` ASC),
  CONSTRAINT `fk_Tecnico_Tecnico1`
    FOREIGN KEY (`fk_padrePersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`DIagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`DIagnostico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`DIagnostico` (
  `pk_idDiagnostico` INT(2) NOT NULL,
  `pk_idOrdenTrabajo` INT(6) NOT NULL,
  PRIMARY KEY (`pk_idDiagnostico`, `pk_idOrdenTrabajo`),
  INDEX `fk_DIagnostico_OrdenTrabajo1_idx` (`pk_idOrdenTrabajo` ASC),
  CONSTRAINT `fk_DIagnostico_OrdenTrabajo1`
    FOREIGN KEY (`pk_idOrdenTrabajo`)
    REFERENCES `mantenimientoPC`.`OrdenTrabajo` (`pk_idOrdenTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Dianostico_parte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Dianostico_parte` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Dianostico_parte` (
  `pk_idDianostico_parte` INT(3) NOT NULL,
  `fk_idOrdenTrabajo` INT(6) NOT NULL,
  `fk_idDiagnostico` INT NOT NULL,
  `fk_idNoSerie` VARCHAR(15) NOT NULL,
  `descripcionProblema` VARCHAR(45) NOT NULL,
  INDEX `fk_Dianostico_parte_OrdenTrabajo1_idx` (`fk_idOrdenTrabajo` ASC),
  PRIMARY KEY (`pk_idDianostico_parte`),
  INDEX `fk_Dianostico_parte_DIagnostico1_idx` (`fk_idDiagnostico` ASC),
  INDEX `fk_Dianostico_parte_Equipo1_idx` (`fk_idNoSerie` ASC),
  CONSTRAINT `fk_Dianostico_parte_OrdenTrabajo1`
    FOREIGN KEY (`fk_idOrdenTrabajo`)
    REFERENCES `mantenimientoPC`.`OrdenTrabajo` (`pk_idOrdenTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dianostico_parte_DIagnostico1`
    FOREIGN KEY (`fk_idDiagnostico`)
    REFERENCES `mantenimientoPC`.`DIagnostico` (`pk_idDiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dianostico_parte_Equipo1`
    FOREIGN KEY (`fk_idNoSerie`)
    REFERENCES `mantenimientoPC`.`Equipo` (`pk_idNoSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Pasos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Pasos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Pasos` (
  `pk_idPaso` INT(3) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `observacion` TEXT NULL,
  `duracion_Paso` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idPaso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Tipo_procedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Tipo_procedimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Tipo_procedimiento` (
  `pk_idTipo_procedimiento` INT(3) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `observacion` TEXT NULL,
  PRIMARY KEY (`pk_idTipo_procedimiento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Procedimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Procedimientos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Procedimientos` (
  `pk_idDianostico_parte` INT(3) NOT NULL,
  `pk_idPaso` INT(3) NOT NULL,
  `pk_idTipo_procedimiento` INT(3) NOT NULL,
  `nombre_Procedimiento` VARCHAR(100) NULL,
  PRIMARY KEY (`pk_idDianostico_parte`, `pk_idPaso`, `pk_idTipo_procedimiento`),
  INDEX `fk_Procedimientos_Dianostico_parte1_idx` (`pk_idDianostico_parte` ASC),
  INDEX `fk_Procedimientos_Pasos1_idx` (`pk_idPaso` ASC),
  INDEX `fk_Procedimientos_Tipo_procedimiento1_idx` (`pk_idTipo_procedimiento` ASC),
  CONSTRAINT `fk_Procedimientos_Dianostico_parte1`
    FOREIGN KEY (`pk_idDianostico_parte`)
    REFERENCES `mantenimientoPC`.`Dianostico_parte` (`pk_idDianostico_parte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Procedimientos_Pasos1`
    FOREIGN KEY (`pk_idPaso`)
    REFERENCES `mantenimientoPC`.`Pasos` (`pk_idPaso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Procedimientos_Tipo_procedimiento1`
    FOREIGN KEY (`pk_idTipo_procedimiento`)
    REFERENCES `mantenimientoPC`.`Tipo_procedimiento` (`pk_idTipo_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Estado_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Estado_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Estado_detalle` (
  `pk_idEstado` INT(2) NOT NULL,
  `pk_idPersonal` INT(3) NOT NULL,
  `pk_idDianostico_parte` INT(3) NOT NULL,
  `pk_idPaso` INT(3) NOT NULL,
  `pk_idTipo_procedimiento` INT(3) NOT NULL,
  PRIMARY KEY (`pk_idEstado`, `pk_idPersonal`, `pk_idDianostico_parte`, `pk_idPaso`, `pk_idTipo_procedimiento`),
  INDEX `fk_Estado_detalle_Estado1_idx` (`pk_idEstado` ASC),
  INDEX `fk_Estado_detalle_Personal1_idx` (`pk_idPersonal` ASC),
  INDEX `fk_Estado_detalle_Procedimientos1_idx` (`pk_idDianostico_parte` ASC, `pk_idPaso` ASC, `pk_idTipo_procedimiento` ASC),
  CONSTRAINT `fk_Estado_detalle_Estado1`
    FOREIGN KEY (`pk_idEstado`)
    REFERENCES `mantenimientoPC`.`Estado` (`pk_idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_detalle_Personal1`
    FOREIGN KEY (`pk_idPersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_detalle_Procedimientos1`
    FOREIGN KEY (`pk_idDianostico_parte` , `pk_idPaso` , `pk_idTipo_procedimiento`)
    REFERENCES `mantenimientoPC`.`Procedimientos` (`pk_idDianostico_parte` , `pk_idPaso` , `pk_idTipo_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Mantenimiento_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Mantenimiento_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Mantenimiento_detalle` (
  `pk_idMantenimiento_detallecol` INT(4) NOT NULL,
  `pk_idOrdenTrabajo` INT(6) NOT NULL,
  `fk_idNoSerie` VARCHAR(15) NOT NULL,
  `fecha` DATE NOT NULL,
  `observaciones` TEXT NULL,
  `Estado_detalle_pk_idEstado` INT(2) NOT NULL,
  `Estado_detalle_pk_idPersonal` INT(3) NOT NULL,
  `Estado_detalle_pk_idDianostico_parte` INT(3) NOT NULL,
  `Estado_detalle_pk_idPaso` INT(3) NOT NULL,
  `Estado_detalle_pk_idTipo_procedimiento` INT(3) NOT NULL,
  PRIMARY KEY (`pk_idMantenimiento_detallecol`, `pk_idOrdenTrabajo`),
  INDEX `fk_Mantenimiento_detalle_OrdenTrabajo1_idx` (`pk_idOrdenTrabajo` ASC),
  INDEX `fk_Mantenimiento_detalle_Equipo1_idx` (`fk_idNoSerie` ASC),
  INDEX `fk_Mantenimiento_detalle_Estado_detalle1_idx` (`Estado_detalle_pk_idEstado` ASC, `Estado_detalle_pk_idPersonal` ASC, `Estado_detalle_pk_idDianostico_parte` ASC, `Estado_detalle_pk_idPaso` ASC, `Estado_detalle_pk_idTipo_procedimiento` ASC),
  CONSTRAINT `fk_Mantenimiento_detalle_OrdenTrabajo1`
    FOREIGN KEY (`pk_idOrdenTrabajo`)
    REFERENCES `mantenimientoPC`.`OrdenTrabajo` (`pk_idOrdenTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_detalle_Equipo1`
    FOREIGN KEY (`fk_idNoSerie`)
    REFERENCES `mantenimientoPC`.`Equipo` (`pk_idNoSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_detalle_Estado_detalle1`
    FOREIGN KEY (`Estado_detalle_pk_idEstado` , `Estado_detalle_pk_idPersonal` , `Estado_detalle_pk_idDianostico_parte` , `Estado_detalle_pk_idPaso` , `Estado_detalle_pk_idTipo_procedimiento`)
    REFERENCES `mantenimientoPC`.`Estado_detalle` (`pk_idEstado` , `pk_idPersonal` , `pk_idDianostico_parte` , `pk_idPaso` , `pk_idTipo_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Rol` (
  `pk_idTrabajo` INT(3) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idTrabajo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`HistorialTrabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`HistorialTrabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`HistorialTrabajo` (
  `pk_idHistorialTrabajo` INT(6) NOT NULL,
  `fk_idTrabajo` INT(3) NOT NULL,
  `fk_idPersonal` INT(3) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`pk_idHistorialTrabajo`),
  INDEX `fk_HistorialTrabajo_Rol1_idx` (`fk_idTrabajo` ASC),
  INDEX `fk_HistorialTrabajo_Personal1_idx` (`fk_idPersonal` ASC),
  CONSTRAINT `fk_HistorialTrabajo_Rol1`
    FOREIGN KEY (`fk_idTrabajo`)
    REFERENCES `mantenimientoPC`.`Rol` (`pk_idTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialTrabajo_Personal1`
    FOREIGN KEY (`fk_idPersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Telefono` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Telefono` (
  `pk_idTelefono` INT NOT NULL,
  `fk_idPersonal` INT(3) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idTelefono`),
  INDEX `fk_Telefono_Personal1_idx` (`fk_idPersonal` ASC),
  CONSTRAINT `fk_Telefono_Personal1`
    FOREIGN KEY (`fk_idPersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Calendario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Calendario` (
  `idCalendario` INT(6) NOT NULL,
  `fecha_mantenimiento` DATE NOT NULL,
  `excepcion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCalendario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
